// ChirpStack v4 fleet codec — GENERATED by device-profiles/profile_to_decoder.py.
// Do not hand-edit; regenerate from the profiles. Decodes the ADR-005 compact payload:
// header [0]=schema [1]=device [2]=flags, then a device-specific fixed-point body (big-endian).
function decodeUplink(input) {
  var b = input.bytes;
  if (!b || b.length < 3) return { errors: ["payload too short"] };
  function u8(i)  { return b[i]; }
  function i8(i)  { var v = b[i]; return v > 0x7f ? v - 0x100 : v; }
  function u16(i) { return (b[i] << 8) | b[i + 1]; }
  function i16(i) { var v = u16(i); return v > 0x7fff ? v - 0x10000 : v; }
  function u32(i) { return (b[i] * 0x1000000) + (b[i + 1] << 16) + (b[i + 2] << 8) + b[i + 3]; }
  function i32(i) { var v = u32(i); return v > 0x7fffffff ? v - 0x100000000 : v; }
  var dev = b[1];
  var out = { schema_version: b[0], simulated: (b[2] & 0x01) !== 0, stale: (b[2] & 0x02) !== 0 };
  if (dev === 4) { // deepsea-dse
    if (b.length < 47) return { errors: ['deepsea-dse payload short'] };
    out.device = "DSE73xx/86xx genset controller";
    out["fuel_pct"] = u8(3 + 0);
    out["batt_v_V"] = u16(3 + 1) / 10;
    out["engine_rpm_rpm"] = u16(3 + 3);
    out["gen_freq_hz_Hz"] = u16(3 + 5) / 10;
    out["gen_l1n_v_V"] = u16(3 + 7) / 10;
    out["gen_l2n_v_V"] = u16(3 + 9) / 10;
    out["gen_l3n_v_V"] = u16(3 + 11) / 10;
    out["gen_l1l2_v_V"] = u16(3 + 13) / 10;
    out["gen_l2l3_v_V"] = u16(3 + 15) / 10;
    out["gen_l3l1_v_V"] = u16(3 + 17) / 10;
    out["mains_freq_hz_Hz"] = u16(3 + 19) / 10;
    out["mains_l1n_v_V"] = u16(3 + 21) / 10;
    out["mains_l2n_v_V"] = u16(3 + 23) / 10;
    out["mains_l3n_v_V"] = u16(3 + 25) / 10;
    out["mains_l1l2_v_V"] = u16(3 + 27) / 10;
    out["mains_l2l3_v_V"] = u16(3 + 29) / 10;
    out["mains_l3l1_v_V"] = u16(3 + 31) / 10;
    out["gen_total_w_W"] = i32(3 + 33);
    out["gen_avg_pf"] = i8(3 + 37) / 100;
    out["gen_pct_power"] = i16(3 + 38) / 10;
    out["engine_run_s_s"] = u32(3 + 40);
    return { data: out };
  }
  if (dev === 5) { // honeywell-eem400-scanned
    if (b.length < 23) return { errors: ['honeywell-eem400-scanned payload short'] };
    out.device = "EEM400-D-MO";
    out["energy_t1_kWh"] = u32(3 + 0) / 100;
    out["v_l1_V"] = u16(3 + 4);
    out["i_l1_A"] = u16(3 + 6) / 10;
    out["v_l2_V"] = u16(3 + 8);
    out["i_l2_A"] = u16(3 + 10) / 10;
    out["v_l3_V"] = u16(3 + 12);
    out["i_l3_A"] = u16(3 + 14) / 10;
    out["p_total_kW"] = u16(3 + 16) / 100;
    out["q_total_kvar"] = u16(3 + 18) / 100;
    return { data: out };
  }
  if (dev === 3) { // honeywell-eem400
    if (b.length < 43) return { errors: ['honeywell-eem400 payload short'] };
    out.device = "EEM400C-D-MO";
    out["t1_total_kwh_kWh"] = u32(3 + 0) / 10;
    out["t1_part_kwh_kWh"] = u32(3 + 4) / 10;
    out["t2_total_kwh_kWh"] = u32(3 + 8) / 10;
    out["v1_V"] = u16(3 + 12) / 10;
    out["v2_V"] = u16(3 + 14) / 10;
    out["v3_V"] = u16(3 + 16) / 10;
    out["i1_A"] = u16(3 + 18) / 10;
    out["i2_A"] = u16(3 + 20) / 10;
    out["i3_A"] = u16(3 + 22) / 10;
    out["p1_kW"] = i16(3 + 24) / 10;
    out["p2_kW"] = i16(3 + 26) / 10;
    out["p3_kW"] = i16(3 + 28) / 10;
    out["q1_kvar"] = i16(3 + 30) / 10;
    out["q2_kvar"] = i16(3 + 32) / 10;
    out["q3_kvar"] = i16(3 + 34) / 10;
    out["p_total_kW"] = i16(3 + 36) / 10;
    out["q_total_kvar"] = i16(3 + 38) / 10;
    return { data: out };
  }
  if (dev === 2) { // rsfsjt-n01
    if (b.length < 5) return { errors: ['rsfsjt-n01 payload short'] };
    out.device = "RS-FSJT-N01";
    out["wind"] = u16(3 + 0) / 100;
    return { data: out };
  }
  if (dev === 1) { // selec-mfm384
    if (b.length < 39) return { errors: ['selec-mfm384 payload short'] };
    out.device = "MFM384-C";
    out["v1n_V"] = u16(3 + 0) / 10;
    out["v2n_V"] = u16(3 + 2) / 10;
    out["v3n_V"] = u16(3 + 4) / 10;
    out["v12_V"] = u16(3 + 6) / 10;
    out["v23_V"] = u16(3 + 8) / 10;
    out["v31_V"] = u16(3 + 10) / 10;
    out["i1_A"] = u16(3 + 12) / 100;
    out["i3_A"] = u16(3 + 14) / 100;
    out["kw1_kW"] = i16(3 + 16) / 10;
    out["kw2_kW"] = i16(3 + 18) / 10;
    out["kw3_kW"] = i16(3 + 20) / 10;
    out["total_kw_kW"] = i16(3 + 22) / 10;
    out["total_kvar_kvar"] = i16(3 + 24) / 10;
    out["pf1"] = i8(3 + 26) / 100;
    out["pf2"] = i8(3 + 27) / 100;
    out["pf3"] = i8(3 + 28) / 100;
    out["avg_pf"] = i8(3 + 29) / 100;
    out["freq_hz_Hz"] = u16(3 + 30) / 100;
    out["total_kwh_kWh"] = u32(3 + 32) / 100;
    return { data: out };
  }
  return { errors: ["unknown device type 0x" + dev.toString(16)] };
}

function encodeDownlink(input) { return { bytes: [] }; }
